spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpashopSecurity?useUnicode=true&characterEncoding=utf-8
    username: cos
    password: cos1234



  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 2n6qrKFE2oE0iytxBNpX
            client-secret: UN7Ik0H9f3
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          google:
            client-id: 14176388205-fhh8tq1gmggon56227nin5ggh2te64jn.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 414538813884802
            client-secret: 529135a51151384dffd0c01970a627fb
            scope:
              - email
              - public_profile
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
